### ISSUE TITLE
Index logging interferes with result output

### ISSUE THREAD

**Issue by ManuDeBuck** [comunica/comunica-actor-init-sparql-hdt#78] opened 2019-08-21 12:31 UTC
When a HDT index has not yet been made while querying, the query-result output interferes with the logging of the generation process of the indexing.

```bash
comunica-sparql-hdt hdtFile@wordnet31.hdt "SELECT * WHERE { ?s ?p ?o } LIMIT 15" -t 
  application/sparql-results+json

(node:19270) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
{"head": {"vars":["s","p","o"]},
Predicate Bitmap in 55 ms 245 us
Count predicates in 210 ms 300 us
Count Objects in 121 ms 765 us Max was: 350837
Bitmap in 27 ms 74 us
Bitmap bits: 5558748 Ones: 2483030
Object references in 683 ms 514 us
Sort lists in 556 ms 884 us
Index generated in 1 sec 654 ms 941 us
"results": { "bindings": [
...
]}}
```

**Comment by rubensworks** [comment] 2019-08-21 12:34
That's actually being caused by the C++ code of HDT: https://github.com/rdfhdt/hdt-cpp
Perhaps this can already be muted somehow.

To be looked into.

**Comment by rubensworks** [comment] 2019-09-03 11:34
I just checked, and this output is generated via stderr, not stdout, so it should not be a big problem.
Considering this a wontfix, as this is something HDT-specific that may actually be useful for users.

**Closed by rubensworks** 2019-09-03 11:34 UTC
Labels: enhancement
